[package]
name = "mlx-internal-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn.workspace = true
quote.workspace = true
darling.workspace = true
proc-macro2.workspace = true

[dev-dependencies]
mlx-rs.workspace = true