[package]
name = "mlx-fast"
version.workspace = true
authors.workspace = true
edition = "2021"

[dependencies]
mlx-rs.workspace = true
mlx-sys.workspace = true
mlx-internal-macros.workspace = true


[dev-dependencies]
float_eq.workspace = true
pretty_assertions.workspace = true
